---

- hosts: all
  connection: local
  gather_facts: false
  tasks:
  - name: Create Project
    os_project:
      state: present
      name: test
      domain_id: default
      endpoint_type: admin
