---

- hosts: all
  connection: local
  gather_facts: false
  tasks:
  - name: Create Project
    os_project:
      auth:
        auth_url: "{{ auth_url }}"
        password: "{{ password }}"
        project: "{{ project_name }}"
        username: "{{ username }}"
      state: present
      name: "{{ osp_project }}"
      domain_id: "{{ osp_domain }}"
